# 第一階段：編譯
FROM node:22-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# --- 在這裡插入兩行，把後端網址寫死 ---
ARG VITE_API_URL=http://3.27.165.128:8001
ENV VITE_API_URL=http://3.27.165.128:8001

RUN npm run build

# 第二階段：生產環境 Nginx
FROM nginx:stable-alpine
# 1. 複製編譯好的靜態檔案
COPY --from=build-stage /app/dist /usr/share/nginx/html
# 2. 複製你的 Nginx 設定檔
COPY nginx.conf /etc/nginx/conf.d/default.conf 

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]